import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/Generated_ActionsWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/GeneratedCategoryWidget8.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/GeneratedLevel_selectWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/GeneratedTopicdescriptionWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/GeneratedTurtoisesWidget1.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/GeneratedBack_to_sel_topicWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedtopicscreenwidget/generated/GeneratedSvg8Widget2.dart';

/* Frame Topic Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTopicScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedSvg8Widget2(),
              ),
              Positioned(
                left: 106.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 53.0,
                child: GeneratedTurtoisesWidget1(),
              ),
              Positioned(
                left: 88.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 60.0,
                child: Generated_ActionsWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 210.0,
                child: GeneratedTopicdescriptionWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 24.0,
                child: GeneratedBack_to_sel_topicWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 44.0,
                child: GeneratedLevel_selectWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 145.0,
                child: GeneratedCategoryWidget8(),
              )
            ]),
      ),
    ));
  }
}
