import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedframe1widget/generated/GeneratedSvg8Widget5.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 36.0,
              top: -23.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 812.0,
              child: GeneratedSvg8Widget5(),
            )
          ]),
    ));
  }
}
