description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  cupertino_icons: "^0.1.3"
  http: ^0.13.4
  cached_network_image: ^3.1.0+1
  webview_flutter: ^2.3.1
  path_drawing: "^0.4.1"
  flutter:
    sdk: "flutter"
dev_dependencies:
  flutter_test:
    sdk: "flutter"
environment:
  sdk: ">=2.7.0 <3.0.0"
flutter:
  assets:
    - "assets/images/"
  fonts:
    - family: "Roboto"
      fonts:
        - asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
    - family: "Playfair Display"
      fonts:
        - asset: "fonts/PlayfairDisplay-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
