import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget2.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget1.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedMagnifyingglassWidget2.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedQuizWidget1.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget5.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget3.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedRegularLWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedPersoncropcircleWidget2.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget6.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedSvg8Widget1.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget7.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedCategoryWidget4.dart';
import 'package:flutterapp/zoohackathonapp/generatedquiztopicscreenwidget/generated/GeneratedNavigationWidget1.dart';

/* Frame Quiz Topic Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuizTopicScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                child: GeneratedSvg8Widget1(),
              ),
              Positioned(
                left: 191.0,
                top: 350.0,
                child: GeneratedCategoryWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 78.0,
                child: GeneratedQuizWidget1(),
              ),
              Positioned(
                left: 263.0,
                top: 83.0,
                child: GeneratedMagnifyingglassWidget2(),
              ),
              Positioned(
                left: 310.0,
                top: 76.0,
                child: GeneratedPersoncropcircleWidget2(),
              ),
              Positioned(
                left: 23.0,
                top: 167.0,
                child: GeneratedCategoryWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 533.0,
                child: GeneratedCategoryWidget2(),
              ),
              Positioned(
                left: 191.0,
                top: 167.0,
                child: GeneratedCategoryWidget3(),
              ),
              Positioned(
                left: 23.0,
                top: 350.0,
                child: GeneratedCategoryWidget4(),
              ),
              Positioned(
                left: 191.0,
                top: 533.0,
                child: GeneratedCategoryWidget5(),
              ),
              Positioned(
                left: 25.0,
                top: 716.0,
                child: GeneratedCategoryWidget6(),
              ),
              Positioned(
                left: 191.0,
                top: 716.0,
                child: GeneratedCategoryWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 750.0,
                child: GeneratedNavigationWidget1(),
              ),
              Positioned(
                left: 247.0,
                top: 222.0,
                child: GeneratedRegularLWidget(),
              )
            ]),
      ),
    ));
  }
}
