import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedsignupscreenwidget/generated/GeneratedSing_upWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedsignupscreenwidget/generated/GeneratedWallpaperWidget1.dart';
import 'package:flutterapp/zoohackathonapp/generatedsignupscreenwidget/generated/Generated_ActionsWidget2.dart';

/* Frame Sign up Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                child: GeneratedWallpaperWidget1(),
              ),
              Positioned(
                left: 26.0,
                top: 123.0,
                child: SingupWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 660.0,
                child: Generated_ActionsWidget2(),
              )
            ]),
      ),
    ));
  }
}
