import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedBackWidget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedBadgesWidget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedRegularLWidget1.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedPawprintWidget16.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedPetWhizWidget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/Generated12Widget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedTurtoiseMasterWidget.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedSvg8Widget3.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedCategoryWidget9.dart';
import 'package:flutterapp/zoohackathonapp/generateduserscreenwidget/generated/GeneratedRoleWidget.dart';

/* Frame User screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                child: GeneratedSvg8Widget3(),
              ),
              Positioned(
                left: 97.0,
                top: 130.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 171.0,
                child: GeneratedCategoryWidget9(),
              ),
/*              Positioned(
                left: 65.0,
                top: 331.0,
                child: GeneratedRoleWidget(),
              ),*/
              Positioned(
                left: 11.0,
                top: 426.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 500.0,
                child: GeneratedPetWhizWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 438.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 446.0,
                child: GeneratedPawprintWidget16(),
              ),
              Positioned(
                left: 29.0,
                top: 500.0,
                child: GeneratedTurtoiseMasterWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 399.0,
                child: GeneratedBadgesWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 438.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 457.0,
                child: GeneratedRegularLWidget1(),
              ),
              Positioned(
                left: 213.0,
                top: 292.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 298.0,
                width: 43.0,
                height: 29.0,
                child: Generated12Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 31.0,
                child: GeneratedBackWidget(),
              )
            ]),
      ),
    ));
  }
}
