import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedsearch_tabwidget/generated/GeneratedContextualMenuWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedsearch_tabwidget/generated/GeneratedSearchFieldWidget.dart';

/* Component search_tab
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearch_tabWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 320.0,
      height: 412.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 20.0,
              top: 60.0,
              child: GeneratedSearchFieldWidget(),
            ),
            Positioned(
              left: 20.0,
              top: 100.0,
              child: GeneratedContextualMenuWidget(),
            )
          ]),
    ));
  }
}
