import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedSvg8Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedThird_pagesWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedNavigationWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedFirst_pagesWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedNewsWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedPersoncropcircleWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedSecond_pagesWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedhomescreen1widget/generated/GeneratedMagnifyingglassWidget.dart';

/* Frame Home Screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedSvg8Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 175.0,
                child: GeneratedFirst_pagesWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 175.0,
                child: GeneratedThird_pagesWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 175.0,
                child: GeneratedSecond_pagesWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 52.0,
                child: GeneratedNewsWidget(),
              ),
              Positioned(
                left: 263.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedMagnifyingglassWidget(),
              ),
              Positioned(
                left: 310.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedPersoncropcircleWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 69.0,
                child: GeneratedNavigationWidget(),
              )
            ]),
      ),
    ));
  }
}
