import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedsigninscreenwidget/generated/GeneratedWallpaperWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedsigninscreenwidget/generated/SingInAction.dart';
import 'package:flutterapp/zoohackathonapp/generatedsigninscreenwidget/generated/GeneratedSign_in_frameWidget.dart';

/* Frame Sign in Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                width: 375.0,
                height: 812.0,
                child: SigninWallpaperWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 159.0,
                width: 320.0,
                height: 373.0,
                child: Sign_in_frameWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 660.0,
                child: Generated_ActionsWidget1(),
              )
            ]),
      ),
    ));
  }
}
