import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedFactWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnswer4Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnser3Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedQuestionWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/Generated15Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnswer1Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedSvg8Widget4.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedBack_to_topicWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnswer2Widget.dart';

/* Frame Question Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuestionScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedSvg8Widget4(),
              ),
              Positioned(
                left: 28.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 200.0,
                child: GeneratedQuestionWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedAnswer1Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedAnswer2Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedAnser3Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GeneratedAnswer4Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 175.0,
                child: GeneratedFactWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 24.0,
                child: GeneratedBack_to_topicWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 41.0,
                child: Generated15Widget(),
              )
            ]),
      ),
    ));
  }
}
