import 'package:flutter/material.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedFactWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnswer4Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnser3Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedQuestionWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/Generated15Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnswer1Widget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedSvg8Widget4.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedBack_to_topicWidget.dart';
import 'package:flutterapp/zoohackathonapp/generatedquestionscreenwidget/generated/GeneratedAnswer2Widget.dart';

/* Frame Question Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuestionScreenWidget extends StatelessWidget {
  int _questionIndex;
  GeneratedQuestionScreenWidget(int n){
    _questionIndex = n;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedSvg8Widget4(),
              ),
              Positioned(
                left: 28.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 200.0,
                child: GeneratedQuestionWidget(_question[_questionIndex]['question']),
              ),
              Positioned(
                left: 28.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GestureDetector(
                    onTap: (){
                      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) =>
                        GeneratedQuestionScreenWidget((_questionIndex + 1)%3),),);
                    },
                    child: GeneratedAnswer1Widget(answerText: _question[_questionIndex]['answers1'])),
              ),
              Positioned(
                left: 198.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GestureDetector(
                    onTap: (){
                      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) =>
                          GeneratedQuestionScreenWidget((_questionIndex + 1)%3),),);
                    },
                    child: GeneratedAnswer2Widget(answerText: _question[_questionIndex]['answers2'])),
              ),
              Positioned(
                left: 198.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GestureDetector(
                    onTap: (){
                      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) =>
                          GeneratedQuestionScreenWidget((_questionIndex + 1)%3),),);
                    },
                    child: GeneratedAnser3Widget(answerText: _question[_questionIndex]['answers3'])),
              ),
              Positioned(
                left: 28.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 100.0,
                child: GestureDetector(
                    onTap: (){
                      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) =>
                          GeneratedQuestionScreenWidget((_questionIndex + 1)%3),),);
                    },
                    child: GeneratedAnswer4Widget(answerText: _question[_questionIndex]['answers4'])),
              ),
              Positioned(
                left: 28.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 175.0,
                child: GeneratedFactWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 24.0,
                child: GeneratedBack_to_topicWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 41.0,
                child: Generated15Widget(),
              )
            ],),
      ),
    ));
  }
}



final _question = const [
  {
    'question':'How many tortoises are there?',
    'answers1' : '5',
    'answers2' : '6',
    'answers3' : '7',
    'answers4' : '8',
  },
  {
    'question':'Tortoises belong to which one of these animal classes?',
    'answers1' : 'Mammals',
    'answers2' : 'Aphibians',
    'answers3' : 'Reptiles',
    'answers4' : 'Hooman',
  },
  {
    'question':'How long does the tortoise live?',
    'answers1' : '5-10 years',
    'answers2' : '50-100 years',
    'answers3' : '500-1000 years',
    'answers4' : '1001-1500 years',
  },
];
